[build]
command = "npm run build"
publish = "dist"

[context.production]
environment = {NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1"}

[context.deploy-preview]
environment = {NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1"}

[dev]
command = "npm run dev"
framework = "#custom"
port = 3000
publish = "build"
targetPort = 8080

# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self';style-src 'self' https://fonts.googleapis.com;font-src 'self' https://fonts.gstatic.com;img-src 'self' localhost:3000;script-src 'self' 'unsafe-eval' https://www.google-analytics.com;"
#     X-Content-Type-Options = "nosniff"
#     X-Frame-Options = "DENY"
#     X-XSS-Protection = "1; mode=block"
